version: "3.8"

services:
  landscape:
    build:
      context: .
      args:
        - REACT_APP_PROTO_JSON_HOST=
        - REACT_APP_PROTO_JSON_PATH=
        - REACT_APP_GITHUB_API_PRJ_URL=
        - REACT_APP_GITLAB_API_PRJ_URL=https://gitlab.acme.dev/api/v4/projects/NNNN/
        - REACT_APP_GITHUB_TOKEN=
        - REACT_APP_GITLAB_TOKEN=
    ports:
      - "5000:80"

  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - 5000:80

  room:
    image: excalidraw/excalidraw-room
    ports:
      - 3003:80

volumes:
  notused:
